- alias: 'lumieres couloir auto on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.detecteur_couloir_sensor
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      # At least one of the following is required.
      - condition: time
        after: '06:30:00'
        before: '09:00:00'
      - condition: time
        after: '17:00:00'
        before: '20:15:00'
      - condition: time
        after: '21:15:00'
        before: '05:10:00'
  action:
    - service: light.turn_on
      entity_id:
      - light.lumieres_couloir_level
      data_template:
        brightness: >
          {% if now().strftime('%H')| int >= 19 %}
          8
          {% elif now().strftime('%H')| int <= 8 %}
          8
          {% else %}
          255
          {% endif %}

- alias: 'extinction lumieres couloir si pas de mouvement'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.detecteur_couloir_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0
  action:
    - service: light.turn_off
      entity_id: light.lumieres_couloir_level

# detection ouverture porte
- alias: 'ouverture porte buanderie'
  initial_state: 'on'
  trigger:
      platform: state
      entity_id: sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control
      to: '22'
  action:
    service: notify.mattermost
    data:
      message: 'ouverture porte buanderie'
      title: 'home assistant event'
