# ##################################
# Summary
# 1. Automatic lights
# 2. Open gates
# 3. Presence simulation
# 4. Alarm change
# 5. Smoke detection
# ##################################


# 1. Automatic lights
- alias: "lumieres couloir auto on"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.detecteur_couloir_sensor
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      # At least one of the following is required.
      - condition: time
        after: "07:00:00"
        before: "20:10:00"
      - condition: numeric_state
        entity_id: sensor.detecteur_couloir_luminance
        below: 10
  action:
    - service: light.turn_on
      entity_id:
      - light.lumieres_couloir_level
      data_template:
        brightness: >
          {% if now().strftime("%H")| int >= 19 %}
          8
          {% elif now().strftime("%H")| int <= 8 %}
          8
          {% else %}
          255
          {% endif %}

- alias: "extinction lumieres couloir si pas de mouvement"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.detecteur_couloir_sensor
      from: "on"
      to: "off"
      for:
        hours: 0
        minutes: 1
        seconds: 0
  action:
    - service: light.turn_off
      entity_id: light.lumieres_couloir_level

# 2. Open gates
- alias: "ouverture porte buanderie"
  initial_state: "off"
  trigger:
      platform: state
      entity_id: sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control
      to: "22"
  action:
    service: notify.ALL_DEVICES
    data:
      message: "ouverture porte buanderie"
      title: "home assistant event"
- alias: "ouverture porte principale"
  initial_state: "off"
  trigger:
      platform: state
      entity_id: sensor.philio_technology_corporation_pst02_a_4_in_1_multi_sensor_access_control
      to: "22"
  action:
    service: notify.ALL_DEVICES
    data:
      message: "ouverture porte principale"
      title: "home assistant event"
- alias: "ouverture porte garage"
  initial_state: "off"
  trigger:
      platform: state
      entity_id: sensor.philio_technology_corporation_pst02_a_4_in_1_multi_sensor_access_control_2
      to: "22"
  action:
    service: notify.ALL_DEVICES
    data:
      message: "ouverture porte garage"
      title: "home assistant event"
      

# 3. Presence simulation
# 3.1. On veut que la lumiere du couloir s'allume aleatoirement 
#   pendant 5/20 minutes aleatoirement
#   toutes les 5/20 minutes
#   - entre 18h et 23h30
#   - entre 6h et 8h
- alias: "simulation de presence lumieres couloir"
  initial_state: "off"
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
   condition: and
   conditions:
     - condition: state
       entity_id: "light.lumieres_couloir_level"
       state: "off"
     - condition: or 
       conditions:
       - condition: time
         after: "06:00:00"
         before: "08:30:00"
       - condition: time
         after: "17:30:00"
         before: "23:30:00"
  action:
    - delay: "00:{{ ((range(5, 20) | random) | int)}}:00"
    - service: light.turn_on
      entity_id:
      - light.lumieres_couloir_level
      data_template:
        brightness: 
          255
    - delay: "00:{{ ((range(5, 20) | random) | int)}}:00"
    - service: light.turn_off
      entity_id: light.lumieres_couloir_level

# 3.2. On veut que les volets EST s'ouvrent a 6h32
# Ouverture partielle : pendant 5 secondes
# uniquement l'été
- alias: "simulation de presence ete ouverture volets est"
  initial_state: "off"
  trigger:
    platform: time
    at: "06:32:00"
  condition:
      condition: template
      value_template: "{{ is_state ('sensor.season', 'summer') }}"
  action:
    - service: cover.open_cover
      entity_id: "cover.est"
    - delay: "00:05:00"
    - service: cover.close_cover
      entity_id: "cover.est"

# 3.2.1, On veut que les volets EST s'ouvrent a 6h32
# tout sauf l'été
- alias: "simulation de presence sauf ete ouverture volets est"
  initial_state: "off"
  trigger:
    platform: time
    at: "06:32:00"
  condition:
      condition: template
      value_template: "{{ not is_state ('sensor.season', 'summer') }}"
  action:
    - service: cover.open_cover
      entity_id: "cover.est"

# 3.3. On veut que les volets EST se ferment a 10h02
# uniquement l'été
- alias: "simulation de presence ete fermeture volets est"
  initial_state: "off"
  trigger:
    platform: time
    at: "10:02:00"
  condition:
      condition: template
      value_template: "{{ is_state ('sensor.season', 'summer') }}"
  action:
    - service: cover.close_cover
      entity_id: "cover.est"

# 3.4. On veut que les volets OUEST s'ouvrent completement a 7h12
- alias: "simulation de presence ouverture volets ouest"
  initial_state: "off"
  trigger:
    platform: time
    at: "07:12:00"
  action:
    - service: cover.open_cover
      entity_id: "cover.ouest"

# 3.5 On veut que les volets OUEST se ferment a 11h45
# uniquement l'été
- alias: "simulation de presence ete fermeture volets ouest"
  initial_state: "off"
  trigger:
    platform: time
    at: "11:45:00"
  condition:
      condition: template
      value_template: "{{ is_state ('sensor.season', 'summer') }}"
  action:
    - service: cover.close_cover
      entity_id: "cover.ouest"

# 3.6 On veut que les volets EST s'ouvrent a 13h45
# uniquement l'été
- alias: "simulation de presence ete ouverture volets est"
  initial_state: "off"
  trigger:
    platform: time
    at: "13:45:00"
  condition:
      condition: template
      value_template: "{{ is_state ('sensor.season', 'summer') }}"
  action:
    - service: cover.close_open
      entity_id: "cover.est"

# 3.7 On veut que les volets EST et OUEST se ferment au couché du soleil
# tout le temps sauf l'été
- alias: "simulation de presence sauf ete fermeture volets ouest"
  initial_state: "off"
  trigger:
      platform: sun
      event: sunset
      offset: '+00:00:00'
  condition:
      condition: template
      value_template: "{{ not is_state ('sensor.season', 'summer') }}"
  action:
    - service: cover.close_cover
      entity_id: "cover.ouest"
    - service: cover.close_cover
      entity_id: "cover.est"

# 3.8. On allume de la musique entre 8h et 23h
# Pendant 30min / 1h
# Toutes les 2 heures
# - alias: "simulation de presence musique"
#   initial_state: "off"
#   trigger:
#       platform: time_pattern
#       hours: "/1"
#   condition:
#       condition: time
#       after: "08:00:00"
#       before: "23:30:00"
#   action:
#       - service: media_player.play_media
#         entity_id: media_player.spotify
#         media_content_id: "spotify:playlist:028abpXSlBkGmHx8FRrrpf"
#         media_content_type: "playlist"
#       - delay: "00:{{ ((range(30, 60) | random) | int)}}:00"

# 4. Alarm triggers
# 4.1. When alarm is enabled, when want to activate door notifications
- alias: "activation alarme"
  initial_state: "on"
  trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'armed_away'
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'armed_home'
  action:
    - service: automation.turn_on
      entity_id: automation.ouverture_porte_buanderie
    - service: automation.turn_on
      entity_id: automation.ouverture_porte_principale
    - service: automation.turn_on
      entity_id: automation.ouverture_porte_garage
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_lumieres_couloir
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_ete_ouverture_volets_est
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_sauf_ete_ouverture_volets_est
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_ete_fermeture_volets_est
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_ouverture_volets_ouest
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_ete_fermeture_volets_ouest
    - service: automation.turn_on
      entity_id: automation.simulation_de_presence_sauf_ete_fermeture_volets_ouest
# 4.2. When alarm is disabled, when want to disactivate door notifications
- alias: "desactivation alarme"
  initial_state: "on"
  trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'disarmed'
  action:
    - service: automation.turn_off
      entity_id: automation.ouverture_porte_buanderie
    - service: automation.turn_off
      entity_id: automation.ouverture_porte_principale
    - service: automation.turn_off
      entity_id: automation.ouverture_porte_garage
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_lumieres_couloir
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_ete_ouverture_volets_est
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_sauf_ete_ouverture_volets_est
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_ete_fermeture_volets_est
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_ouverture_volets_ouest
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_ete_fermeture_volets_ouest
    - service: automation.turn_off
      entity_id: automation.simulation_de_presence_sauf_ete_fermeture_volets_ouest

# 5. Smoke Detection
- alias: "Smoke detection alert"
  initial_state: "on"
  trigger:
      - platform: state
        entity_id: binary_sensor.fibaro_system_fgsd002_smoke_sensor_sensor
        from: "off"
        to: "on"
  action:
    service: notify.ALL_DEVICES
    data:
      message: "DETECTION FEU / CHALEUR / FUMEES"
      title: "DETECTION FEU"


# 6.1 On veut que les volets OUEST se ferment a 13h
- alias: "fermture_auto_volets_ouest"
  initial_state: "off"
  trigger:
    platform: time
    at: "13:01:00"
  action:
    - service: cover.close_cover
      entity_id: "cover.ouest"
# 6.2 On veut que les volets EST s'ouvrent a 13h
- alias: "ouverture_auto_volets_est"
  initial_state: "off"
  trigger:
    platform: time
    at: "13:00:00"
  action:
    - service: cover.open_cover
      entity_id: "cover.est"
# 6.3 On veut que les volets EST se ferment a 9h
- alias: "fermeture_auto_volets_est"
  initial_state: "off"
  trigger:
    platform: time
    at: "09:00:00"
  action:
    - service: cover.close_cover
      entity_id: "cover.est"

## 7. Guirlande Noel
- alias: 'Allumage guirlande matin'
  trigger:
      platform: sun
      event: sunrise
      offset: '-02:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.shellyplug_s_168387
    - delay: '03:00:00'
    - service: switch.turn_off
      entity_id: switch.shellyplug_s_168387
- alias: 'Allumage guirlande soir'
  trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.shellyplug_s_168387
    - delay: '05:00:00'
    - service: switch.turn_off
      entity_id: switch.shellyplug_s_168387

## 8. Chauffage semis
- alias: 'Allumage Chauffage semis'
  trigger:
      platform: numeric_state
      entity_id: sensor.philio_technology_corporation_pst02_a_4_in_1_multi_sensor_temperature_2
      below: 16
  action:
    - service: switch.turn_on
      entity_id: switch.shellyplug_s_168387
- alias: 'Extinction Chauffage semis'
  trigger:
      platform: numeric_state
      entity_id: sensor.philio_technology_corporation_pst02_a_4_in_1_multi_sensor_temperature_2
      above: 16
  action:
    - service: switch.turn_off
      entity_id: switch.shellyplug_s_168387
