- alias: 'lumieres couloir auto on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.detecteur_couloir_sensor
      to: 'on'
  condition:
    condition: or
    conditions:
      # At least one of the following is required.
      - condition: time
        after: '06:10:00'
        before: '09:00:00'
      - condition: time
        after: '17:00:00'
        before: '20:15:00'
      - condition: time
        after: '21:00:00'
        before: '05:10:00'
  action:
    - service: light.turn_on
      entity_id:
      - light.lumieres_couloir_level
      data_template:
        brightness: >
          {% if now().strftime('%H')| int >= 19 %}
          8
          {% elif now().strftime('%H')| int <= 8 %}
          8
          {% else %}
          255
          {% endif %}

- alias: 'lumieres couloir auto off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.detecteur_couloir_sensor
      to: 'off'
  action:
    - service: light.turn_off
      entity_id:
      - light.lumieres_couloir_level
