- platform: command_line
  covers:
    salon:
      command_open: curl -X POST http://192.168.1.17:8080/action/1/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/1/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/1/down
    cuisine:
      command_open: curl -X POST http://192.168.1.17:8080/action/2/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/2/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/2/down
    parents:
      command_open: curl -X POST http://192.168.1.17:8080/action/3/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/3/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/3/down
    amis:
      command_open: curl -X POST http://192.168.1.17:8080/action/4/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/4/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/4/down
    enfant1:
      command_open: curl -X POST http://192.168.1.17:8080/action/5/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/5/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/5/down
    enfant2:
      command_open: curl -X POST http://192.168.1.17:8080/action/6/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/6/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/6/down
    sdb:
      command_open: curl -X POST http://192.168.1.17:8080/action/7/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/7/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/7/down
    atelier:
      command_open: curl -X POST http://192.168.1.17:8080/action/8/up
      command_stop: curl -X POST http://192.168.1.17:8080/action/8/stop
      command_close: curl -X POST http://192.168.1.17:8080/action/8/down

- platform: group
  name: living
  entities:
    - cover.cuisine
    - cover.salon
- platform: group
  name: enfants
  entities:
    - cover.enfant1
    - cover.enfant2
- platform: group
  name: chambres
  entities:
    - cover.enfant1
    - cover.enfant2
    - cover.sdb
    - cover.amis
    - cover.parents
- platform: group
  name: est
  entities:
    - cover.enfant2
    - cover.sdb
    - cover.amis
    - cover.cuisine
- platform: group
  name: ouest
  entities:
    - cover.enfant1
    - cover.parents
    - cover.salon
    - cover.atelier
- platform: group
  name: tout
  entities:
    - cover.ouest
    - cover.est
 
# - platform: template
#   covers:
#     salon_template:
#       friendly_name: "Salon template"
#       set_cover_position:
#         service: script.cover_percent
#         data_template:
#           entity_id: cover.salon
#           position: "{{position}}"
#           total_time: 27
#       optimistic: true
