#- platform: yeelight
#  devices:
#    192.168.1.8:
#      name: chambre_nicolas
#      transition: 1000
#      use_music_mode: True
#      save_on_change: False
- platform: flux_led
  devices:
      192.168.1.21:
          name: leds_salon
          mode: "rgb"
