- platform: onkyo
  host: 192.168.1.6
  name: amplifier
- platform: plex
  show_all_controls: false
  use_episode_art: true
  remove_unavailable_clients: true
  client_remove_interval: 600
# - platform: spotify
#   client_id: !secret secret_spotify_client_id
#   client_secret: !secret secret_spotify_client_secret
