# Weather prediction
- platform: yr
- platform: time_date
  display_options:
    - 'time'
- platform: apcupsd
  resources:
    - bcharge
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - outputv
    - status
    - timeleft
    - tonbatt
