- platform: netatmo
# Weather prediction
- platform: yr
- platform: time_date
  display_options:
    - 'time'
- platform: apcupsd
  resources:
    - bcharge
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - outputv
    - status
    - timeleft
    - tonbatt
- platform: season
  type: astronomical
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home/choco/datas
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
