title: My Awesome Home test
views:
    # View tab title.
  - title: Example
    panel: true
    # Makes the first card fill the view
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
          _test_
