resources:
  - url: /local/monster-card.js
    type: js
title: Home Assistant
views:
  - title: Maison
    panel: false
    cards:
        - type: entities
          title: Volets roulant
          show_header_toggle: false
          entities:
            - entity: cover.living
              name: Salon + Cuisine
            - entity: cover.chambres
              name: Chambres
            - entity: cover.tout
              name: Tout
        - type: picture-entity
          title: Camera
          entity: camera.garage_exterieur
          camera_view: live
        - type: sensor
          entity: sensor.netatmo_indoor_temperature
          name: Température Salon
          graph: line
          hours_to_show: 48
        - type: sensor
          entity: sensor.netatmo_toit_temperature
          name: Température Toit
          graph: line
          hours_to_show: 48
        - type: sensor
          entity: sensor.netatmo_indoor_noise
          name: Bruit intérieur
          graph: line
          detail: 2
        - type: alarm-panel
          entity: alarm_control_panel.ha_alarm

  - title: Meteo
    panel: false
    cards:
        - type: weather-forecast
          entity: weather.montagnat
        - type: history-graph
          title: 'Temperatures sur 24h'
          hours_to_show: 24
          refresh_interval: 10
          entities:
            - entity: sensor.netatmo_indoor_temperature
              name: Temperature intérieure
            - entity: sensor.netatmo_toit_temperature
              name: Temperature extérieure
        - type: history-graph
          title: 'Temperatures sur une semaine'
          hours_to_show: 168
          refresh_interval: 10
          entities:
            - entity: sensor.netatmo_indoor_temperature
              name: Temperature intérieure
            - entity: sensor.netatmo_toit_temperature
              name: Temperature extérieure

  - title: Volets
    panel: false
    cards:
        - type: entities
          title: Volets roulant (individuel)
          show_header_toggle: false
          entities:
            - entity: cover.salon
              name: Salon
            - entity: cover.cuisine
              name: Cuisine
            - entity: cover.parents
              name: Parents
            - entity: cover.amis
              name: Amis
            - entity: cover.enfant1
              name: !secret prenom_enfant1
            - entity: cover.enfant2
              name: !secret prenom_enfant2
            - entity: cover.sdb
              name: Salle de bain enfants
            - entity: cover.atelier
              name: Atelier
        - type: entities
          title: Volets roulant (groupes)
          show_header_toggle: false
          entities:
            - entity: cover.living
              name: Salon + Cuisine
            - entity: cover.enfants
              name: Enfants
            - entity: cover.chambres
              name: Chambres
            - entity: cover.est
              name: Volets Est
            - entity: cover.ouest
              name: Volets Ouest
            - entity: cover.tout
              name: Tous les volets

  - title: Lumieres
    panel: false
    cards:
        - type: light
          entity: light.lumieres_couloir_level
          name: Lumières couloir
        - type: light
          entity: light.leds_salon
          name: Leds Salon

  - title: Automatisations
    panel: false
    cards:
        - type: entities
          title: Lumieres 
          show_header_toggle: false
          entities:
            - entity: automation.lumieres_couloir_auto_on
            - entity: automation.extinction_lumieres_couloir_si_pas_de_mouvement
        - type: entities
          title: Simulation de presence 
          show_header_toggle: false
          entities:
            - entity: automation.simulation_de_presence_lumieres_couloir
            - entity: automation.simulation_de_presence_ete_ouverture_volets_est
            - entity: automation.simulation_de_presence_sauf_ete_ouverture_volets_est
            - entity: automation.simulation_de_presence_ete_fermeture_volets_est
            - entity: automation.simulation_de_presence_ouverture_volets_ouest
            - entity: automation.simulation_de_presence_ete_fermeture_volets_ouest
            - entity: automation.simulation_de_presence_sauf_ete_fermeture_volets_ouest

  - title: Electricité
    panel: false
    cards:
      - type: custom:monster-card
        show_empty: true
        card:
          type: glance
          title: Onduleur
        filter:
          include:
            - entity_id: "sensor.*ups*"
      - type: custom:monster-card
        show_empty: true
        card:
          type: glance
          title: Linky
        filter:
          include:
            - entity_id: "sensor.linky*"
      - type: custom:monster-card
        show_empty: true
        card:
          type: glance
          title: Batterie niveau faible
        filter:
          include:
            - entity_id: "*battery_level*"
              state: '<= 25'
            - attributes:
                battery: '<= 25'
            - attributes:
                battery_level: '<= 25'
      - type: history-graph
        title: 'Consommation électrique'
        hours_to_show: 720
        entities:
            - entity: sensor.linky_yesterday
              name: Consommation électrique
  - title: Serveur
    panel: false
    cards:
        - type: entities
          title: Lumieres 
          show_header_toggle: false
          entities: 
            - entity: sensor.memory_use_percent
            - entity: sensor.disk_use_percent
            - entity: sensor.disk_use_percent_home_choco_datas
